#!/bin/bash

FILE=$1
shift
EXTRA=$@

NAME="${FILE%.*}"

if [ "$NAME" == "$FILE" ]; then
    FILE="${FILE}.cpp"
fi

COMPILE="g++ -std=c++20"
OPT="-O3"
FLAGS="-Wall -Wextra -pedantic -Wold-style-cast -Werror"

set -x

$COMPILE -o $NAME $FILE $OPT $FLAGS $EXTRA
