#!/bin/bash

EXEC="$1"
TRACEDIR="$2"
OUTDIR="$3"

MAXJOBS=16
CORES=$(nproc)
JOBS=$(( CORES < MAXJOBS ? CORES : MAXJOBS ))

mkdir -p ${OUTDIR}
find "$TRACEDIR/" -name "*_trace.gz" | parallel -j "$JOBS" ./run $EXEC {} "$OUTDIR"
